# Generated by Django 5.1.2 on 2024-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
